//
//  Event+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - Event properties

extension Event {

    @NSManaged var eventDate: Date?
    @NSManaged var taken: Bool // cannot mark as optional because Objective-C compatibility issues

    @NSManaged var plan: Plan?

}

