//
//  Event+AlecrimCoreDataAttributes.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData


// MARK: - Event query attributes

extension Event {

    static let eventDate = AlecrimCoreData.NullableAttribute<Date>("eventDate")
    static let taken = AlecrimCoreData.NullableAttribute<Bool>("taken")

    static let plan = AlecrimCoreData.NullableAttribute<Plan>("plan")

}

// MARK: - AttributeProtocol extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: Event {

    var eventDate: AlecrimCoreData.NullableAttribute<Date> { return AlecrimCoreData.NullableAttribute<Date>("eventDate", self) }
    var taken: AlecrimCoreData.NullableAttribute<Bool> { return AlecrimCoreData.NullableAttribute<Bool>("taken", self) }

    var plan: AlecrimCoreData.NullableAttribute<Plan> { return AlecrimCoreData.NullableAttribute<Plan>("plan", self) }

}

// MARK: - NSManagedObjectContext extensions

extension NSManagedObjectContext {

    var events: AlecrimCoreData.Table<Event> { return AlecrimCoreData.Table<Event>(context: self) }

}

