//
//  Plan+CoreDataProperties.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

// MARK: - Plan properties

extension Plan {

    @NSManaged var additionalInfo: String?
    @NSManaged var endDate: Date?
    @NSManaged var fireDate: Date?
    @NSManaged var inProgress: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var medicineKind: String?
    @NSManaged var medicineName: String?
    @NSManaged var otherUser: String?
    @NSManaged var periodicity: Int16 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged var startDate: Date?
    @NSManaged var unitsPerDose: Int16 // cannot mark as optional because Objective-C compatibility issues

}

