//
//  Plan+AlecrimCoreDataAttributes.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData


// MARK: - Plan query attributes

extension Plan {

    static let additionalInfo = AlecrimCoreData.NullableAttribute<String>("additionalInfo")
    static let fireDate = AlecrimCoreData.NullableAttribute<Date>("fireDate")
    static let medicineKind = AlecrimCoreData.NullableAttribute<String>("medicineKind")
    static let medicineName = AlecrimCoreData.NullableAttribute<String>("medicineName")
    static let otherUser = AlecrimCoreData.NullableAttribute<String>("otherUser")
    static let periodicity = AlecrimCoreData.NullableAttribute<Int16>("periodicity")
    static let unitsPerDose = AlecrimCoreData.NullableAttribute<Int16>("unitsPerDose")

}

// MARK: - AttributeProtocol extensions

extension AlecrimCoreData.AttributeProtocol where Self.ValueType: Plan {

    var additionalInfo: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("additionalInfo", self) }
    var fireDate: AlecrimCoreData.NullableAttribute<Date> { return AlecrimCoreData.NullableAttribute<Date>("fireDate", self) }
    var medicineKind: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("medicineKind", self) }
    var medicineName: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("medicineName", self) }
    var otherUser: AlecrimCoreData.NullableAttribute<String> { return AlecrimCoreData.NullableAttribute<String>("otherUser", self) }
    var periodicity: AlecrimCoreData.NullableAttribute<Int16> { return AlecrimCoreData.NullableAttribute<Int16>("periodicity", self) }
    var unitsPerDose: AlecrimCoreData.NullableAttribute<Int16> { return AlecrimCoreData.NullableAttribute<Int16>("unitsPerDose", self) }

}

// MARK: - NSManagedObjectContext extensions

extension NSManagedObjectContext {

    var plans: AlecrimCoreData.Table<Plan> { return AlecrimCoreData.Table<Plan>(context: self) }

}

